# [[pages]]
# path = "pages/app.py"
# name = "Platform"
# icon = "âœ¨"

# [[pages]]
# path = "pages/compliancy.py"
# name = "Compliancy"
# icon = "ğŸ’¯"

# [[pages]]
# path = "pages/chat.py"
# name = "Chat"
# icon = "ğŸ•µï¸â€â™€ï¸"

# [[pages]]
# path = "pages/contact.py"
# name = "Contact Us"
# icon = "âœ‰ï¸"