[[pages]]
path = "app.py"
name = "Blaire"
icon = "ğŸ•µï¸â€â™€ï¸"

[[pages]]
path = "pages/bomai.py"
name = "Compliancy"
icon = "ğŸ’¯"

[[pages]]
path = "pages/platform.py"
name = "Platform"
icon = "âœ¨"

[[pages]]
path = "pages/contact.py"
name = "Contact Us"
icon = "âœ‰ï¸"
