[[pages]]
path = "app.py"
name = "Assistant"
icon = "ğŸ•µ"

[[pages]]
path = "pages/bomai.py"
name = "BOM Compliancy"
icon = "ğŸ’¯"

[[pages]]
path = "pages/contact.py"
name = "Contact Us"
icon = "âœ‰ï¸"
